version: '3.7'

services:
  notebooks:
    build: container
    platform: linux/amd64
    volumes:
      - ./notebooks:/opt/notebooks
    ports:
      - "8888:8888"
    command: jupyter notebook --allow-root --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888
